name: Run linter

on:
  pull_request:
    branches:
      - develop

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
